version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: imphnen-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: imphnen
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminsecret
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d imphnen"]
      interval: 10s
      timeout: 5s
      retries: 5 
volumes:
  db-data:
