name: Deploying Go

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.sql"
  pull_request:
    branches: [main]

jobs:
  db-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose file to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/docker-compose.yml"
          target: "~/app"
          strip_components: 1
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Starting deployment..."

            cd ~/app

            echo "Creating .env file..."
            cat > .env << EOL
            KOLOSAL_API_KEY=${{ secrets.KOLOSAL_API_KEY }}
            PORT=${{ secrets.PORT }}
            DSN=${{ secrets.DSN }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            EOL

            echo "Shutting down current containers..."
            docker compose down

            echo "Delete unused images..."
            docker system prune -f

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting containers..."
            docker compose up -d

            echo "Deployment completed!"

  on-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: System Failed 
        run: echo "The triggering workflow failed"

  go-deploy:
    runs-on: ubuntu-latest
    needs: db-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.25.4"
      - name: Build binary
        run: |
          cd backend
          GOOS=linux GOARCH=amd64 go build -o imphnen cmd/main.go
      - name: Stop service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            systemctl stop go-deploy
      - name: Copy Binary File to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "backend/imphnen"
          target: "~/app"
          strip_components: 1
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            systemctl restart go-deploy
