name: Deploy Docker Image

on:
  workflow_run:
    workflows: [Build and Publish Docker Image]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose file to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/docker-compose.yml"
          target: "~/app"

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            cd ~/app/backend

            echo "Creating .env file..."
            cat > .env << EOL
            KOLOSAL_API_KEY=${{ secrets.KOLOSAL_API_KEY }}
            PORT=${{ secrets.PORT }}
            DSN=${{ secrets.DSN }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            EOL

            echo "Shutting down current containers..."
            docker compose down

            echo "Delete unused images..."
            docker system prune -f

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting containers..."
            docker compose up -d

            echo "Deployment completed!"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: System Failed 
        run: echo "The triggering workflow failed"
